apiVersion: sloth.slok.dev/v1
kind: PrometheusServiceLevel
metadata:
  name: request-availability
  namespace: monitoring
spec:
  service: "app"
  labels:
    owner: "yzdann"
    repo: "yzdann/jakub"
    tier: "2"
  slos:
    - name: "requests-availability"
      objective: 99.9
      description: "Common SLO based on availability for HTTP request responses."
      sli:
        events:
          errorQuery: sum(rate(response_status{status=~"(5..|429)"}[{{.window}}]))
          totalQuery: sum(rate(response_status[{{.window}}]))
      alerting:
        name: MyServiceHighErrorRate
        labels:
          category: "availability"
        annotations:
          summary: "High error rate on 'myservice' requests responses"
        pageAlert:
          disable: true
        ticketAlert:
          disable: true
