apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app
  namespace: default
  labels:
    name: app
    env: stage
spec:
  jobLabel: hello
  namespaceSelector:
    matchNames: 
    - stage
  selector:
    matchLabels:
      app: app
  endpoints:
  - port: http
