apiVersion: v1
kind: Service
metadata:
  labels:
    app: app
  name: app
  namespace: stage
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: app
  type: ClusterIP
