name: Continuous Integration

on:
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main
    - release/*
jobs:
  build-and-push-image:
    name: Build and Push Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    if: contains(github.ref, 'release')
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build container image
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}
        registry: docker.pkg.github.com
        repository: ${{ github.repository }}/peeleh
        tag_with_sha: true
        tag_with_ref: true
