name: Continuous Integration

on:
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main
    - release/*
jobs:
  build-and-push-image:
    name: Build and Push Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    if: contains(github.ref, 'release')
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Prints the current branch name
      run:  echo "##[set-output name=release_version;]$(echo ${GITHUB_REF##*/})"
      id: extract_branch

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build container image
      uses: docker/build-push-action@v2
      with:
        context: "app"
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/app:latest
          ghcr.io/${{ github.repository_owner }}/app:${{ steps.extract_branch.outputs.release_version }}
